name: app_fidelizacion
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=2.18.5 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  get: ^4.6.5
  firebase_messaging: ^14.6.2
  firebase_core: ^2.13.1
  intl: ^0.17.0
  cupertino_icons: ^1.0.2
  flutter_local_notifications: ^14.1.1
  firebase_auth: ^4.6.3
  http: ^1.1.0
  cloud_firestore: ^4.8.2
  device_info_plus: ^9.0.2
dev_dependencies:
  flutter_test:
    sdk: flutter
  
  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true
  
  assets:
    - static/

  fonts:
    - family: Monserrat
      fonts:
        - asset: static/fonts/Montserrat-VariableFont_wght.ttf