// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAXlL8DbXGyKtGjDMK2FO13TArXqdjB0zw',
    appId: '1:300754219920:web:826c3e78bd1418e06eb915',
    messagingSenderId: '300754219920',
    projectId: 'fidelizacion-app',
    authDomain: 'fidelizacion-app.firebaseapp.com',
    storageBucket: 'fidelizacion-app.appspot.com',
    measurementId: 'G-WW2NG39DBC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBjj5kXjF3LltbOF4gaLRGKyl0zgyc-zCI',
    appId: '1:300754219920:android:191823f177325dfe6eb915',
    messagingSenderId: '300754219920',
    projectId: 'fidelizacion-app',
    storageBucket: 'fidelizacion-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAOjkY6z_urrSarrLq-p8sT_Mg42Af4Nzk',
    appId: '1:300754219920:ios:984010eedb59bab66eb915',
    messagingSenderId: '300754219920',
    projectId: 'fidelizacion-app',
    storageBucket: 'fidelizacion-app.appspot.com',
    androidClientId: '300754219920-othb0giprb09a8116ek46frvqhe53m75.apps.googleusercontent.com',
    iosClientId: '300754219920-8o2q139uhdbjr4iar331imdnjvl3i13r.apps.googleusercontent.com',
    iosBundleId: 'com.example.appFidelizacion',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAOjkY6z_urrSarrLq-p8sT_Mg42Af4Nzk',
    appId: '1:300754219920:ios:984010eedb59bab66eb915',
    messagingSenderId: '300754219920',
    projectId: 'fidelizacion-app',
    storageBucket: 'fidelizacion-app.appspot.com',
    androidClientId: '300754219920-othb0giprb09a8116ek46frvqhe53m75.apps.googleusercontent.com',
    iosClientId: '300754219920-8o2q139uhdbjr4iar331imdnjvl3i13r.apps.googleusercontent.com',
    iosBundleId: 'com.example.appFidelizacion',
  );
}
